/**
 * @fileOverview Schemas and types for the security awareness chatbot flow.
 * This file defines the input and output structures for the AI-powered security chatbot.
 * It is kept separate from the flow logic to comply with Next.js "use server" constraints.
 */

import { z } from 'zod';

/**
 * Defines the schema for the input to the security awareness chatbot flow.
 */
export const SecurityAwarenessInputSchema = z.object({
  /** The user's question about security. Should be concise. */
  query: z.string().describe('The user query about security. Be concise.'),
  /** The desired language for the response. Defaults to 'en' (English). */
  language: z.enum(['en', 'pidgin']).optional().default('en'),
});

/**
 * The type representing the input for the securityAwarenessChatbot function.
 */
export type SecurityAwarenessInput = z.infer<typeof SecurityAwarenessInputSchema>;

/**
 * Defines the schema for the output from the security awareness chatbot flow.
 */
export const SecurityAwarenessOutputSchema = z.object({
  /** The concise and actionable security advice generated by the AI. */
  advice: z.string().describe('Concise and actionable security advice.'),
});

/**
 * The type representing the output of the securityAwarenessChatbot function.
 */
export type SecurityAwarenessOutput = z.infer<typeof SecurityAwarenessOutputSchema>;
