/**
 * @fileoverview Input/output schemas for the Co-pilot (security awareness chatbot).
 */

import { z } from 'zod';

export const ChatTurnSchema = z.object({
  role: z.enum(['user', 'assistant']),
  content: z.string().max(4000),
});

/**
 * Input to the Co-pilot.
 */
export const SecurityAwarenessInputSchema = z.object({
  /** The user's question about security. */
  query: z.string().max(4000).describe('The user query about security.'),
  /** The desired language for the response. Defaults to 'en' (English). */
  language: z.enum(['en', 'pidgin']).optional().default('en'),
  /** Recent conversation turns, oldest first (memory). */
  history: z.array(ChatTurnSchema).max(20).optional(),
});

export type SecurityAwarenessInput = z.input<typeof SecurityAwarenessInputSchema>;

/**
 * Output of the Co-pilot.
 */
export const SecurityAwarenessOutputSchema = z.object({
  /** The concise and actionable security advice generated by the AI. */
  advice: z.string().describe('Concise and actionable security advice.'),
});

export type SecurityAwarenessOutput = z.infer<typeof SecurityAwarenessOutputSchema>;
